version: '3.8'

services:
  # web:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - chroma
  #     - ollama

  chroma:
    image: chromadb/chroma
    volumes:
      - ./chroma_data:/chroma/chroma
    ports:
      - "8000:8000"

  # ollama:
  #   image: ollama/ollama
  #   volumes:
  #     - ./ollama_data:/root/.ollama
  #   ports:
  #     - "11434:11434"

